# Generated by Django 5.0.3 on 2024-03-18 03:16

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('plan', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Themes',
                'verbose_name_plural': 'Themes',
                'db_table': 'themes',
                'ordering': [builtins.id],
            },
        ),
    ]
