# Generated by Django 5.0.3 on 2024-03-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appThemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.AlterModelOptions(
            name='themes',
            options={'verbose_name': 'Themes', 'verbose_name_plural': 'Themes'},
        ),
    ]
