# Generated by Django 5.0.3 on 2024-03-18 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appThemes', '0002_category_alter_themes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='category_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appThemes.category'),
        ),
    ]
