# Generated by Django 5.0.3 on 2024-03-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPupils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Student image'),
        ),
    ]
