# Generated by Django 5.0.3 on 2024-03-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPupils', '0002_pupil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/', verbose_name='Student image'),
        ),
    ]
